### ISSUE TITLE
Date in Avatar not back-propagating

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#250]
![image](https://github.com/MyLife-Services/mylife-maht/assets/42016062/b3caaaae-cc4e-4e2e-bd89-1dab489bab8a)
Guess there is an issue with calendar.  Not sure how 4/1 became 4/29.  Perhaps Leap Year Day bug/calculation.
Separately I did enter a birthday when I registered but it apparently didn't take at registration. I have since entered a fake DOB just to play around with it and noticed this issue. (edited)

**Comment by Mookse** [comment]
Notes: could be either:
- lost in instructionset (i.e., instructionsets for avatar and biographer should be updated on BOD update---looking for other conceptual ways to lock this field down appropriately)
- as such was detached from biographer instructionset AND cosmos (update did not make it to core)

**Comment by Whammo22** [comment]
When I registered I put in 5/22/1980 but when I finally got in, the field was blank so I didn't think my DOB existed.   As a test, I entered 04/01/1979, it updated.   The date stuck after logging in and out.   Then I asked it my birthday and it said April 29th. Which doesn't match anything I input.

**Comment by Mookse** [comment]
Excellent - thanks! That confirms my suspicions for this one. Planning to register and account-create for full list of volunteers by eod Monday, so this is high-priority for inclusion in pre-pilot

**Comment by Mookse** [comment]
- Pipe _through_ biographer, even if interface shows differently

**Comment by Whammo22** [comment]
> * Pipe _through_ biographer, even if interface shows differently

I don't understand what this means.

**Comment by Mookse** [comment]
Sorry @Whammo22 That comment was just for myself :) Going to take a stab at this now.

**Comment by Mookse** [comment]
Okay, not huge, but larger build than I can incorporate tonight for .13; notes to self on remedy

- endpoint /bots/:botId
- payload includes node: `dob`
- payload, upon receipt should be directed to 
  - self (i.e., sniff the var and add to generic personal vars -- this one is system identified, so it will "overwrite" all `avatar` class `experience` variables
  - `mylife-factory.mjs` where it gets propagated to core data structures **and** gets posted to personal biographer instruction set
- **Note** I feel like this var should get unique treatment for any number of reasons so for Product `Member Avatar` rethink alteration process

**Comment by Mookse** [comment]
This is obviated by newer mechanics, going to close
