### ISSUE TITLE
Add Favicon on site for easier identification in Browser

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#252]
It's difficult to identify which tab is My Life aka HRP when browser has multiple tabs open.

Favicon is put on the site so that the site feels branded and it is easy to return to tab to resume usage of the site without opening an additional tab.

No alternatives are known at this time.

Currently the default world icon is shown as part of my Chrome browser.

**Comment by Mookse** [comment]
now where oh where did my favicon go... there used to be one, should be easy to remediate, incorporating in .13
