### ISSUE TITLE
Provide more room to menu at top of Chat Window

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#253]
**Describe the bug**
Avatar-id, Biographer and Scrapbook icons are hidden at the top of the chat menu

**To Reproduce**
1. Go to (https://humanremembranceproject.org/members)
2. Click on Chat Window
3. Mouse over the top of the Chat window to unhide the icons

**Expected behavior**
Icons would be more visible without placing cursor over them to unhide them

**Screenshots**
![Screenshot 2024-07-05 130808 Hidden Menu](https://github.com/MyLife-Services/mylife-maht/assets/174664002/ab1e4faa-0c08-492b-9027-27e6e5372e73)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 126.0.6478.127 (Official Build) (64-bit)

**Smartphone (please complete the following information):**

**Additional context**
These icons seem duplicative of what is on the right and may not serve any beneficial purpose. Perhaps the icons can just be moved to the right to save the real estate.

**Comment by Mookse** [comment]
Ruthless - I love it! This has been back-back-burnered as my nod to the idea that Apple has excellent interface ideas, but I have no idea how to use or UX them independently. This probably _won't_ make it into .13, and I might recommend that we temporarily remove from `alpha` while we work on improving it. 
It is in no way strictly required to accomplish bot-switching. However, **that** ticket needs nearer-term address on my part.
