### ISSUE TITLE
Failure to follow through when reporting significant events

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#261]
Chat bot fails to follow through on promise when asked for significant events on a day when they aren't found on first attempt.  It reports that it will find information but then stalls.

**To Reproduce**
1. Go to Community Project Manager
2. Click on Virtual Me
3. Type in chat window, "What significant thing happened on May 22  1980.
4. See Screenshots with output.

**Expected behavior**
I expected it first to query my records and not find any and then to look at public records. If nothing was found it might search additional and then provide some additional information after a short period of time. It does this but then fails to produce results.

It does however think that Mt. St Helens did continue to erupt on may 22nd, 1980 but the original report was that it started to erupt on May 18th 1980 even though it may have continued to erupt.

While it seems to have noticed there wasn't any prior recorded information in my data it does seem to have recognized possibly that I asked the question previously and has associated it to common record.  If so I would expect it to be citing this common record.

**Screenshots**
See desktop: ![Screenshot 2024-07-09 123831 May 22nd 1980 Query Desktop](https://github.com/MyLife-Services/mylife-maht/assets/174664002/a2d00b14-a4e7-47e0-91ee-6efb2d93be01)
See Mobile: 
![Significant May 22nd 1980 Mobile](https://github.com/MyLife-Services/mylife-maht/assets/174664002/fce4784c-1281-4c00-834e-852eb2b1d91d) This query was done initially on mobile and then I replicated it on Desktop afterwards so that is possibly were the mis-information was introduced.

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 126.0.6478.127 (Official Build) (64-bit)

**Smartphone (please complete the following information):**
 - Device: Moto G Stylus 2023
 - OS: Android 14
 - Browser: Chrome
 - Version Latest version

**Additional context**

**Comment by Mookse** [comment]
Moving this one over to testing - all of the models I think are now equipped with the ability to web search by default, but we should certainly test and address if not (and determine and assign which bots should have the ability)
