### ISSUE TITLE
Registration: Text Formatting Adjustment

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#263]
**Describe the bug**
Add hard return during registration to increase readability.

**To Reproduce**
1. Go to ['...'](https://humanremembranceproject.org/members)
2. Click on chat box
3. Type in "Register me" 
4. Click Submit
5. Wait for Chat to out put required information

**Expected behavior**
Required information  would be listed clear and concisely.  Additional text should be below the 3 required items with a hard return

**Screenshots**

![Image](https://github.com/MyLife-Services/mylife-maht/assets/174664002/7c09aa76-cca9-4997-bdcd-88819ba0ab6d)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome
 - Version 126

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mookse** [comment]
- [x] Need to ensure that items are wrapped in \<p> or other block element to display correctly
- [x] .marked() causing disruption
