### ISSUE TITLE
Unable to Select "Journler" from Memoir Team "+" Dropdown

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#268]
**To Reproduce**

1. Steps to reproduce the behavior:
2. ogin to the application.
3. Click on the "+" symbol under the Memoir Team section.
4. Observe the dropdown menu showing both "Dairy" and "Journler" options.
5. Attempt to select "Journler."
6. Journler" cannot be selected .
7. Once "Dairy" is selected, "Dairy" option disappears from the dropdown.
8. Only "Journler" remains in the dropdown after "Dairy" is selected.

**Actual result**

1. Journler" cannot be selected .
2. Once "Dairy" is selected, "Dairy" option disappears from the dropdown.
3. Only "Journler" remains in the dropdown after "Dairy" is selected.

**Comment by Mookse** [comment]
Excellent! Initial build will remove this item, but captured for fix in re-release of journaler
