### ISSUE TITLE
File Upload Not Working under Scrapbook -> Files

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#270]
**To Reproduce**

1. Navigate to the Scrapbook section.
2. Go to the Files tab.
3. Attempt to upload a file.
4. Upload window opens to select file
5. Select a file and click on update button.

 **Expected behavior**
Selected file should be uploaded and store user details.

**Actual Result:**
Selected file is not shown under files.

**Comment by Mookse** [comment]
Might have gotten lucky here and this is only a display issue - upon refreshing the page, the item I uploaded appeared. In this instance, I will ensure return payload is being dynamically added to file list.

**Comment by Mookse** [comment]
- [x] upload functionality successful for new member with no vectorstore originally
- [x] create Vectorstore on account creation `createAccount`
  - currently inside Member Avatar `mInit` on-demand creation, but prior -or- _just_ prior to initial assistant creation.
  - vectorstore read is coming through
  - [x] FORCE test-account _spritz_ to regenerate store, as nothing pertinent
  - [x] ERROR: logical case missing where threadId is null from frontend but NOT in bot `mylife-avatar.mjs` line 103: `conversation = conversation ?? this.getConversation(threadId)`
- [x] OpenAI vectorestore issue: threads created before vectorstore (and possibly file uploads) haven't access
  - [x] confirmed: so long as vector store attached to GPT when thread is born, new files are available
  - [x] decision: create vectorstore at `createAccount` - I only see allusions that cost is per storage, and an empty vs is empty? Obviously pay attention (1Gb included)
  - [x] set vectorstoreId for member in `mylife-agent-factory.mjs` _merely_ patches `core` document see [comment](https://github.com/MyLife-Services/mylife-maht/issues/270#issuecomment-2241096817)
    - referenced in `mCreateBot` direct from core, in order to call `mGetAIFunctions`.
    - May even be that it wasn't that the specific vectorstore wasn't attached, but no toolsearch endpoint was available to GPT
- [x] `mCreateBot` should require access to `vectorstore_id`
- [x] avatar this.#bots not being updated on updates - seems to call openai every selection
  - [x] remove `metadata` from `mUpdateBot` decision to update bot, is secondary and will trigger unnecessarily
- [x] large-scale memory updates review
  - [x] Avatar must update local session memory in `mylife-avatar.mjs`
    - [x] `updateBot` - **note**: mBot() updates `avatar.bots`
    - [x] `updateInstructions`
      - [x] vectorstore not associated on version update
  - [x] Factory `mUpdateBot` must update Cosmos
    - `const updatedBot = await factory.dataservices.updateBot(botData)`
- [x] refresh file list on frontend upon receipt from server
  - [x] Avatar `upload` not returning correct fileList after adding
  - [x] refresh button does not refresh list for files unavailable
  - [x] frontend not reparsing list after upload

**Comment by Mookse** [comment]
``` javascript
	set vectorstoreId(vectorstoreId){
		/* validate vectorstoreId */
		if(!vectorstoreId?.length)
			throw new Error('vectorstoreId required')
		this.dataservices.patch(this.core.id, { vectorstoreId, }) /* no await */
		this.core.vectorstoreId = vectorstoreId /* update local */
	}
```
