### ISSUE TITLE
Bot Greetings

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#276]
# Bot Greetings

## Suggested Functionality and UX

- [x] upon `bots.setActiveBot()` add payload node `greeting`
  - [x] internally, use Bot.greeting(static=true) generates random internal hello from `this.greetings`
- [x] add `greetings` to bots in db 
  - [x] biographer version 1.7
  - [x] journaler version 1.2
  - [x] diary version 1.0
  - [x] pa version 1.1
- [x] response refactored (backend && frontend)
  - [x] `validateRegistration`
    - [x] `functions.mjs`
    - [x] `mylife-avatar.mjs`
    - [x] `guest.mjs` (frontend)
  - [x] `greetings`
    - [x] `functions.mjs`
    - [x] `mylife-avatar.mjs`
      - [x] Avatar `greeting()`
      - [x] Q `greeting()` create overload?
    - [x] `bot-agent.mjs`
      - [x] `mBotGreeting`
      - [x] `mBotCreate`
      - [x] Bot `greeting()`, `get greetings`
      - [x] Bot Agent `greeting()`, `get greetings`
    - [x] `bots.mjs` (frontend)

## Referenced Issues

- #293 
- #408 

## Current UX-API interactions

The current bot greetings are untenable for Alpha Pilot. The scheme functionally is tech-mapped as follows

- Member selects bot (default appearance is avatar, but could discuss last used)
  - MVP limited to either talking to biographer-bot or talking to avatar
    - scrapbook and other libraries are not bots, they are just data collections (for now, or always if graced solely into Member Avatar, which is where I propose in other issues)
- Server API parses server event and returns greeting in payload
  - **complicating** elements include:
    - Member Avatar (as hosted on MyLife and represented as a personalized instance of AgentFactory) must discern between dynamic and static request by default as well as decision-making about its own needs [human writes: 'aww, you can do better than that...!' and guess what, it's always LLM-time!]
    - Session-Sensitivity: gates on server load must be in place, not every hello can be a dynamic call to OpenAI; need value vs impact case study
- FE parses greeting and displays to member

- **note**: line items previously
  - finalize Q-initial greeting &/or test via url param `dyn`

**Comment by Vudum** [comment]
Welcome message can be updated to any of the following.

1. 	•	"Welcome back, Lakshmi! How can I assist you today?” or “Welcome Lakshmi Need assistance with anything specific today?" Or "Hi Lakshmi! It's great to see you again. What can I help you with today?"
2. 	•	"Good day, Lakshmi! Let's make today productive. How can I assist?"
3. 	•	"Hey Lakshmi! I'm here to help you achieve your goals. What would you like to start with?"
4. 	•	"Hello Lakshmi! Based on your recent activity, you might be interested in [suggested task]. Need help with that?"
5. 	•	"Welcome back, Lakshmi! How about we continue where you left off?"

On top of the welcome message, design can be slightly modified to give options to the user right after login. Idea behind this screenshot is to give a glance on how we could change to give multiple options to the user very quickly. 
![image](https://github.com/user-attachments/assets/7c62c00d-9559-4d45-a50f-74f66c5dcc01)
