### ISSUE TITLE
Fix About page so it loads

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#321]
About page doesn't load properly.

1. Go to 'About' https://humanremembranceproject.org/about
2. Wait for page to load.

**Expected behavior**
Page would fully load.  

**Screenshots**

![Image](https://github.com/user-attachments/assets/db50e23e-a4c3-46b6-a59a-ec61ba2b1ee1)

**Desktop (please complete the following information):**
 - OS:Windows 11
 - Browser Chrome
 - Version 126 64 Bit edition

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Mookse** [comment]
**note** @Whammo22 can you confirm that this only happens when logged in? I am able to get the about page when logged out, but logged in it spins

**Comment by Whammo22** [comment]
I didn't try it while logged out.   It may be the same experience.  I
apologize for not testing.
