### ISSUE TITLE
Personal Avatar name change doesn't take fully

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#322]
Upon entering a new Avatar name it is updated in the header but then the text box reverts to the default. The chatbot window isn't updated.

**To Reproduce**
1. Go to 'My Life'
2. Click on 'Arrow' to expand the Avatar Section
3. Click in my personal-avatar box and update the name
4. Observe the header will display the new name
5. Change bots to Biographer or Scrapbook
6. Revert to Avatar bot.  The Chatbot window still displays the default My personal-avatar name
7. Bot Name textbox name is reverted to My personal-avatar

**Expected behavior**
Bot name will be updated across chatbot and bot windows upon updating them.

**Screenshots**

![Image](https://github.com/user-attachments/assets/c0ac0d73-fbed-43fe-a229-ea0b1bd02237)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 126 64 Bit

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Whammo22** [comment]
![Screenshot_20240819-181537](https://github.com/user-attachments/assets/38ebc109-3c14-4319-9f42-4d5c23ccbd43)
Just tried new username and got this error.

**Comment by Whammo22** [comment]
@Mookse Happens on Desktop as well.

**Comment by Mookse** [comment]
Gack - I think this might be a ghost in your account, as I can't replicate it on either my real or test account.
@Whammo22 I'm pretty convinced this is related to renaming your member-id, we can use this ticket for non-secure info, I'll push this to this weekend's 0.18, see if I can see where the data is disconnecting

**Comment by Whammo22** [comment]
I get the 🪲 badge 🏆.   While I see this is an edge case we may need to consider if this could resurface and what the impact would be if similar request was made from a user.  I know the drop-down is going away eventually but changing username might be a thing.

**Comment by Mookse** [comment]
@Whammo22 Great work on this one - I hate to say that I forgot exactly where we left it - I think we conquered the first part when we removed your ghost avatar, and the second is this lingering problem I'm going to look at today, which is about frontend session connection management. If this isn't a consistent error, i.e., if you try again and it doesn't break, we can close this

**Comment by Whammo22** [comment]
Sorry I forgot to retest my I'll try it.
