### ISSUE TITLE
Choose Library or Scrapbook as Bot name

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#323]
Use of Library in Chatbot is confusing since the Bot window refers to the section as Scrapbook and also library right under the header.

**To Reproduce**
1. Go to 'My Life' https://humanremembranceproject.org/members
2. Click on 'Scrapbook' bot
3. Read name in the Chatbot window

**Expected behavior**
Naming convention would be the same between the bot and the chatbot window for continuity.  The names shouldn't differ, especially since the other two existing bots match, name-wise.

**Screenshots**
![Image](https://github.com/user-attachments/assets/757ebfec-14f9-498f-a8c8-f083c410d389)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 126 64 Bit

**Smartphone (please complete the following information):**

**Additional context**
"Library" is more formal so possibly Scrapbook would be the better option. Repository, Vault or Locker are other options as well.

**Comment by Mookse** [comment]
Routing ticket to new location, as it will solve issues of naming for time-being #340
