### ISSUE TITLE
Organize Biographer Categories

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#324]
Create order to Biographer Categories

**To Reproduce**
1. Go to 'MyLife'
2. Click on 'Biographer'
3. Look at list of categories

**Expected behavior**
They would be in alphabetical order or have some other categorization

**Screenshots**

Arts and Culture:
Art
Culture
Entertainment
Fashion
Literature
Music

Personal Life:
Family
Genealogy
Health
Hobbies
Pets
Relationships

Academics and Education:
Academics
Ideas
Philosophy
Science

Work and Business:
Business
Tech
Work/Career

Society and Community:
Digital Self
Politics
Religion
Social Justice
Volunteering/Philanthropy

Leisure and Lifestyle:
Food
Sports
Travel

Psychology and Well-being:
Psychology

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**
Maybe have three states.  This way the biographer can suggest things you like more often. Sometimes things you're open to and avoid things you don't want to share about. Like, Open, Hide.

**Comment by Mookse** [comment]
I will fix alpha order for this right away, and I really like this idea, so I'm going to attach the suggestion to my open biographer bot update ticket
