### ISSUE TITLE
Read GPT Functions from JSON

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#325]
Convert the current hard-coded mechanic to a versioned read of the JSON directory allocated to actions and functions. Code is triggered at opening of `globals.mjs` which may itself not be the correct destination; I'm not sure at the moment why I was hesitant to put it in `mylife-llm-service.mjs`

**Comment by Vudum** [comment]
@Mookse  I think this issue can be closed isn't it? I was able to add a memory from GPT directly to MyLife. In GPT schema, we add Json content e.g. for creating a memory. Once memory is added through GPT, memory is seen in MyLife.

**Comment by Mookse** [comment]
@Vudum This is a technical issue, so is not required for alpha, but essentially we do not have the functions in our database yet, they are hard-coded in the codebase. There is no security issues or concerns, but a technical hack, so I'm leaving this open.
Ah, and a **note**: These types of tickets often find their way to the technical security grouping projects, the current one being Talc - which reminds me to set up a new project for Gypsum, as Talc will really encompass however far we get by Alpha, and the next project will be more well-designed.
