### ISSUE TITLE
Remove "personal" from the chat window

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#327]
Currently when a bot loads it says personal-avatar or personal-biographer and Library.

**To Reproduce**
1. Go to 'MyLife' https://humanremembranceproject.org/
2. Click on 'Login'
3. Scroll down to 'passphrase' field and enter passphrase

**Expected behavior**
It would say "I am _**dynamicname**_, avatar for Mark Schwanke"
"I am _**dynamicname**_, biographer for Mark Schwanke"
"I am the Scrapbook for Mark Schwanke"

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 127 64 bit edition

**Smartphone (please complete the following information):**

**Additional context**
Initially it would use the default names for Avatar and Biographer but would update once you rename the dots to tie the bot and chat windows together.  In the text entry field it would say "Type your message to _**dynamicname**_"

**Comment by Mookse** [comment]
Should be fixed as I have changed the placeholder to read their names
