### ISSUE TITLE
Leaving page idle causes Hardcoded interface to show

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#328]
If you allow your computer to go to sleep whilst logged in it appears that the hardcoded interface appears once you wake the computer and the browser loads.  Upon refreshing the page you are taken to a logged out state

**To Reproduce**
1. Go to 'MyLife' https://humanremembranceproject.org/members
2. Click on 'Login'
3. Scroll to 'Passphrase' field and enter passphrase
4. Put computer in sleep mode
5. Wake the computer to show browser and MyLife page
6. Notice that the hardcoded bots are shown.  See attached image

**Expected behavior**
Page will refresh periodically to ensure that the login state is understood. If computer is gone idle and no typing, clicking or scrolling has occurred for XX minutes then unsaved things will be autosaved and then the user will be logged out. 

**Screenshots**
[Video of refreshing page after waking my computer back up from a sleep.  Off screen i am reloading the page using the refresh button in Chrome browser](https://somup.com/cZj1b2GwjO)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Chrome
 - Version 127 64 Bit edition

**Smartphone (please complete the following information):**

**Additional context**
You will notice that it appears logged in after waking the computer but upon refreshing the page the button changes from Logout to Login.

**Comment by Mookse** [comment]
Session end now forces member back to login
