### ISSUE TITLE
Reliving Memories Reformatting

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#330]
**Describe the bug**
Reliving Memories results in a long paragraph that isn't ideal for readability.  The text should be split up more into paragraphs to give user a more pleasurable experience.

**To Reproduce**
1. Go to 'My Life' https://humanremembranceproject.org/members
2. Click on 'Login'
3. Scroll down to 'chat box' and enter passphrase
4. Click on Scrapbook
5. Expand Memories
6. Choose a memory
7. Click box "relive memory"
8. Read memory in the chat box

**Expected behavior**
Memory will be displayed in a format where like ideas are encapsulated in paragraphs.  It should not be formatted into one long paragraph.  Any CTA  should be their own bullets or list as a separate paragraph.  Instead of being included at the end of the paragraph, buried in the text that will not likely result in person adding on to their memory

**Screenshots**
![Image](https://github.com/user-attachments/assets/3d66287b-3ed3-4ab4-a205-a932195a6727)

Focus on Green box of text.  

**Desktop (please complete the following information):**
 - OS: Windows 11 64 Bit
 - Browser Chrome
 - Version 127 64 bit

**Smartphone (please complete the following information):**

**Additional context**
Oddly the text box didn't change to the Scrapbook bot. It remained on the personal-avatar bot. Any responses would seemingly be recorded by the avatar bot, though based on prior experience it seems non functional so it might not add on to the story in a way that it claims.

**Comment by Mookse** [comment]
This solution is going to be comprised of a few steps:

- [x] `bots.mjs`
  - [x] remove normal chat inputs when reliving
  - [x] unsetActiveItem
  - [x] cancel to end
  - [x] `loading` bar
  - [x] confirmation of summary (in simplicity, just a bar that states)
- [x] `bots.css`
