### ISSUE TITLE
Reliving Memory is not showing copy of entered text in Scrapbook Chat Window

### ISSUE THREAD

**Issue by Whammo22** [MyLife-Services/mylife-maht#331]
**Describe the bug**
When I relive a memory and add new details utilizing the Scrapbook bot it doesn't display a copy of my entered text like it does when I organically use the Biography or Scrapbook bots. Not having a way to see the text I've entered and having it disappear immediately makes me concerned. Additionally upon pressing the NEXT button the text just disappears and it appears as though nothing is happening. There is no indication that something is happening behind the scenes and the inputted text is being looked at.  In the video provided the entered text doesn't seem to even be absorbed by MyLife so what I typed was just gone.  In previous attempts in the same bot I did make new entries that appeared to add on to my memory bank however I didn't make mention to other key words from already banked memory so perhaps an inability to draw a correlation seemed to prevent a new memory from being recorded and feedback provided by the bot.

**To Reproduce**
Watch video

**Expected behavior**
1. I expect to see a copy of my entered text.
2.  I expect the information to show with at least paragraphs formatting.
3. I expect to see some type of visual indicator that after pressing Next button that information is being processed.  Not having this feedback could lead to people refreshing the page or something else leading to poor  experience.  In the video it takes approximately 17 seconds from the point that the Next button is pressed and my text disappears for it to reappear indicating that the text has been parsed and possibly something has happened. 

**Screenshots**
(https://somup.com/cZjjFVGaFZ)

**Desktop (please complete the following information):**
 - OS: Windows 11 64 bit
 - Browser Chrome
 - Version 127 64 Bit

**Smartphone (please complete the following information):**

**Additional context**
I am doing this entry to record how much time after I click the next button that it begins to show a response. I am also curious as to why the text I have entered doesn’t show in the chat window like I am able to see with using the bottom text entry field. It seems to only put a copy of the text less the formatting when using the Primary chat field.

**Comment by Mookse** [comment]
This solution is similar to `changeTitle`; I'll lay it out here

- [x] `mylife-llm-provider.mjs` in avatar.frontendInstruction memory prepare the update when appropriate (see below)
- [x] frontend
  - [x] `members.mjs` create instruction response handlers for updateItemSummary
  - [x] call `bots.mjs` function `updateItem()` to update summary content
    - [x] requires { itemId, summary, } fields

``` js
avatar.frontendInstruction = {
  command: 'updateItemSummary',
  itemId,
  summary: updatedSummary,
}
```

**Comment by Mookse** [comment]
Really fun to fix this one @Whammo22 - it might not be perfect, but it's dynamically incorporating and updating the story content summary as well
