### ISSUE TITLE
Relive Memory

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#362]
# Key Functionality Relive Memory

Member shall be able to relive memory; this ticket represents the catalog of bugs and enhancements required for the Alpha MVP to achieve specifications

## Related Issues

- [x] fix: prune item before sent in payload from living memory - ONLY send when updated
- [x] fix: relive broken when updating since it does not return the correct payload to the stream that needs to output the next part; note - could just treat differently when reliving? tbd
- [x] fix: issue with cached failures from update and changeTitle (although everything else is working, including the instructions)
- [x] relive bot instructions should include that summary starts conversation as well
- [x] on end, need to restore relive memory function to that popup button
- [x] fix: not ending on backend, but is receiving request
- [x] fix frontend not clearing inputs (too soon in display times, may need flag)
- [x] narrator can end memory
  - [x] instructions (see comment)
  - [x] create `endReliving` action (i.e., JSON and mjs assignments) in biographer
- [x] endReliveMemory
  - [x] close button
  - [x] print responses
  - [x] on success, null out mRelivingMemory
  - [x] frontend command receipt
- [x] #394 
- [x] member input box now appearing prior to first content
- [x] clear chat system when starting

**Comment by Mookse** [comment]
Instruction added at end of LIVING memory
```markdown
- After the last dramatic segment, share a moral interpretation of memory. After which, if reliving is still active, call `endReliving` action.
```
