### ISSUE TITLE
Delete memory functionality issues

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#370]
Identified few issues with delete memory functionality.

Issue 1
===========

1. Login to MyLife
2. Click on any memory delete button
3. Click cancel button when pop up message is shown to the user (Are you sure you want to delete this item?)
4. Click on same memory delete button as in step 2. 
5. Click cancel button when pop up message is shown to the user (Are you sure you want to delete this item?)
6. At this point, memory is opened and becomes active which is not expected.

Issue 2
===========

1. Login to MyLife
2. Click on any memory delete button
3. Click cancel button when pop up message is shown to the user (Are you sure you want to delete this item?)
4. Click on same memory as in step 2 to open the memory 
5. Click cancel button when pop up message is shown to the user (Are you sure you want to delete this item?) which is not expected

Issue 3
===========

1. Click on scrapbook
2. Click on Memory bar
3. Click on desired Memory
4. Memory popup window is shown to the user.
5. Close the memory
6. Ensure Active: "<Memory title>" above the chat is shown to the user.
7. Delete the same memory as in step 3.
8. Click Ok to the pop up message.
9. Refresh the memories
10. Deleted memory is removed from the list
11. BUT Ensure Active: "<deleted memory>" is still shown to the suer.

**Comment by Vudum** [comment]
Tested on v.0.0.21
FYI @Mookse Let me know if we have to create multiple tickets for this. For now, this is just a placeholder for memory issues.

**Comment by Mookse** [comment]
There was an issue with the member canceling out of the confirmation, so this was fixed in #423
