### ISSUE TITLE
Skip to Next Scene button is not responding in welcome screen

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#375]
**Describe the bug**
Skip to Next Scene button is not responding in welcome screen

**To Reproduce**
Login to MyLife
Click on Run Tutorial
In welcome screen, click on Skip to Next Scene button 

**Expected behavior**
Should navigate to next scene

ENV: 0.0.22

**Comment by Mookse** [comment]
no functionality to support

- [x] remove next scene button
  - [x] `experience.mjs` remove `skip` listeners, functionality should remain when there are scenes
  - [x] `layout.html` commented out `experience-skip`
