### ISSUE TITLE
MyLife passphrase is case insensitive.

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#376]
Reset Mylife passphrase containing capital letters.
Login with all small letters.
Visitor is allowed to login.

**Comment by Mookse** [comment]
Should be resident perhaps in the stored procedure on DB - will address, allowing for both to be utilized, but defaulting differently, and allowing toggle in Avatar

- [x] `functions.mjs`: direct challenge, sets session property `challengeOutcome` and attempts to initialize session
- [x] `session.mjs`
  - [x] remove function `challengeAccess`
  - [x] create setter `set challengeOutcome(outcome)` 
- [x] `core.mjs`: add `challengeAccess` to class `MyLife` **only**
- [x] `mylife-agent-factory.mjs` bifurcate `challengeAccess`
  - [x] class `MyLifeFactory`:  add `challengeAccess` to route to proxy
  - [x] class `BotFactory`:  add `challengeAccess` (as proxy) to datacore
- [x] `mylife-data-service.mjs` require and pass `caseInsensitive` parameter that defaults to `false`
- [x] `mylife-datamanger.mjs` require and pass `caseInsensitive` parameter that defaults to `false`
- [x] in Cosmos, SP defaults to wrong sensitivity
  - [x] corrected: `function checkMemberPassphrase(passphrase, caseInsensitive=false)`

**Comment by Mookse** [comment]
```javascript
/**
* Runs challenge Access routine for login and authentications
* @param {string} mbr_id - The member id to challenge
* @param {string} passphrase - The passphrase to resolve challenge
* @param {boolean} caseInsensitive - Whether to ignore case in passphrase, defaults to `false`
* @returns {Promise<boolean>} - `true` if challenge is successful
*/
async challengeAccess(mbr_id, passphrase, caseInsensitive=false){
  const { resource: result } = await this.#containers['members']
	  .scripts
	  .storedProcedure('checkMemberPassphrase')
	  .execute(mbr_id, passphrase, caseInsensitive)
  return result
}
```

**Comment by Mookse** [comment]
@Vudum This is implemented in local testing, but we'll have a push tomorrow with this included
