### ISSUE TITLE
Optimize Chat History Management for OpenAI Context

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#380]
Thread history is how the llm memory is achieved -- the thread is the memory, but it's too much traffic and highly costly to send the entire history every time. So leveraging the thread content ON open ai is preferable

Also, members can consent out of conversation storage on MyLife

The conversation history need only be written to me thread when the previous one isn't found.

**Comment by Mookse** [comment]
Included in recent update
