### ISSUE TITLE
Biographer selection are not the same after login back to MyLife

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#386]
Selection is here
![image](https://github.com/user-attachments/assets/bbdd1c4c-6e93-477e-b2d6-e496243a8ec0)

Logout and login back, here is new the selection shown to the member.
![image](https://github.com/user-attachments/assets/b4d041c2-0933-459c-907c-ecba8a3bdfe7)

**Comment by Mookse** [comment]
interests were not dynamically moving thread, and had issues storing, fixed in #402
