### ISSUE TITLE
Memory is not being saved by Biographer-bot 

### ISSUE THREAD

**Issue by sheikita** [MyLife-Services/mylife-maht#387]
After submitting my memory to the biographer-bot, there is no record or message that confirms it was saved and is available to review. The expected behavior was for the bot to indicate that memory was saved.
I had to ask the bot to save it and got the below message:

![Screen Shot 2024-10-02 at 6 23 39 PM](https://github.com/user-attachments/assets/16731121-6250-474e-a9c6-b373aa0493fa)

Desktop
 - OS: Mac
 - Browser: chrome

@sheikita I made a comment about what this frontend error message represents. Here is the following near-term fix for better tracking and error-handling on these matters

- [x] store list of `run_id` in Conversation object in DB, simple comma-delimited string
fixed in #402

**Comment by Mookse** [comment]
@Vudum This occurs when a request of the LLM model is made, and for some reason an error return from the LLM provider. There are no error logs from OpenAI, or rather, at the moment, it would imply that I would have to violate privacy.
However! I am going to rewrite the opening of the ticket to imply that we store the run_id (which is the ID of the external processing) with a conversation, so we can isolate and identify the error, and this would be a quick solution.

**Comment by Mookse** [comment]
Fixed in 0.0.25
