### ISSUE TITLE
Make Memory Action

### ISSUE THREAD

**Issue by sheikita** [MyLife-Services/mylife-maht#388]
The one line memory is not being saved by the bot.  And if you request the bot to save the one line memory, it assumes that it needs to be incorporated to the recent memory that was saved.

![Screen Shot 2024-10-02 at 6 46 40 PM](https://github.com/user-attachments/assets/be59c294-dac1-4b03-8e8a-4305ec6683d1)

@Mookse note: see #429 specifically

**Comment by Mookse** [comment]
Honestly, not even having this problem half the time, now Scriz wants to save everything - I'm happy to have a session to go over some of the possibilities here

**Comment by Mookse** [comment]
@sheikita While this one has been half-handled with the copy/paste button, I'll leave it open for now, as we could get back to offering options to the member giving direction on when memories are preferred to be "made"

**Comment by Mookse** [comment]
Included in #429 and #424
