### ISSUE TITLE
Unable to edit memory title via pop up window header

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#389]
**Issue 1:**
Double click any memory in the memory list and edit the memory title.
Member is able to edit the save the title.
Open memory the same memory using single click.
Try to edit the title.
Member is unable to edit the title. **(This is not expected)**
Refresh the memories.
Open the same memory using single click and edit the memory title.
This time member is able to edit the title.

**Issue 2**
Open a memory using single click.
Update the memory title from pop up window header.
Title in the pop up window is updated.
Close the popup window.
Active: <updated title is shown>
But memory title in memories remains the same old title. **(This is not expected)**
Open the same memory.
Pop up window show updated/new title.
Close the pop up window.
Active:<Memory title is reverted back to original title> **(This is not expected)**

**Comment by Vudum** [comment]
Let me know if we have to create two issues here.

**Comment by Mookse** [comment]
I believe this is happening because of improper name (or referencing or double-naming) of the popup title bar and the item title bar
