### ISSUE TITLE
Relive Placeholder

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#394]
# Relive Placeholder
Open any memory and click on relive memory.
Relive memory is shown in the chat.
But it shows Next button in relive memory instead of Update.

- [x] placeholder on memberInput: `What did I get wrong? Are there important details I missed?`

**Comment by Mookse** [comment]
@Vudum Can you confirm something for me? The functionality here _should_ work as follows:
By default upon initial display, button should read NEXT
If typing occurs in the chat input area (maybe 2+chars?) the button text should change to UPDATE

**Comment by Vudum** [comment]
Yes, this now works exactly as you said, Update appears if I type >2 characters otherwise Next is shown to the member.
