### ISSUE TITLE
Platform is not handling consistently all prompts available at the Memory Functionaliy

### ISSUE THREAD

**Issue by sheikita** [MyLife-Services/mylife-maht#396]
@Mookse
See comment below, this issue now kills two birds
 
- [x] #298 

The rotating/changing teal prompts are not being handled consistently by the platform thus the resulting outputs are different.  For example, if you select "The what was happening int the world at the time?", the prompt is showed as an output from the bot. Now, if you select "at the time, I was living at", it is showed in the chat input field. 

The expected behavior should be that the prompt is added into the chat input field so the user can add more information. 

![Screen Shot 2024-10-03 at 11 28 12 AM](https://github.com/user-attachments/assets/4e65a84b-05ba-4013-a9aa-a059c9167aa7)

**Desktop (please complete the following information):**
 - OS: Mac
 - Browser Chrome

**Comment by Mookse** [comment]
In discussion with @sheikita and @Vudum I believe for the moment we only need to close off the artery that allows for these `shadows` to be serverside-generated. We will leave them as human prompts only in Alpha. Lightly co-opting an earlier issue that addresses this.
