### ISSUE TITLE
Enhance Memory Save Feedback and User Guidance

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#401]
Implement a clear and obvious confirmation method to inform users when a memory is saved, and also provide guidance on how to save a memory.

**Comment by Vudum** [comment]
If a member edit a memory directly and saves the memory using disk icon. No indication that memory is saved, disk icon remains same.

**Comment by Vudum** [comment]
So, two issues here.

1. When quill edit button is clicked, no change in icon so the member is ready to edit the memory.
2. When save button is clicked, no indication to member that memory is updated and saved.

**Comment by Mookse** [comment]
Related to #424 I have completed part of this one - I'll snag the code to grab the following functionality for the quill:

- [x] on quill select or double-click in content, QUILL ACTIVATES (enlarge and color)
  - if clicked when activated blocks editing and returns to normal, NO SAVE
- [x] DISKETTE will show checkmark when saved then fade back to disk after 2secs
