### ISSUE TITLE
Clear distinctions on the roles and responsibilities for each Agent 

### ISSUE THREAD

**Issue by Vudum** [MyLife-Services/mylife-maht#421]
The following features are AI agents Avatar, Biographer, Relive, Q ?
What's their responsibility?
@sheikita for this one, can you give me some vision on where this occurs? Is this the introduction feature you described or is this greeting-related? Could it be solved in the options (/more info) box of each bot? Let me know your thoughts

**Comment by Mookse** [comment]
@sheikita I think the rollover may cover this for the immediate, please let me know if you have other thoughts on implementation.

**Comment by sheikita** [comment]
@Mookse 
I will suggest to group the expected behaviors for our agents based on the below user workflow.
1.  User enters the platform-  
* Default agent behavior for Avatar: Greet the user and suggest activities within MyLife that user can do. i.e. Hey: should we start creating a a new memory? Should I connect you with your Memory bot?  - The goal is to drive user engagement and remind users of our available functionalities.
* **Default** response when the user prompts "What is your role Avatar. " The current response does not relate to our current mission. See screenshot.  
![Screen Shot 2024-11-11 at 12 49 08 PM](https://github.com/user-attachments/assets/7da6c70b-3563-4cdf-9a1a-b919cc17ba5e)

2.  User interacts with the platform
*  User prompts that wants to create a memory.  Agent should respond back something along the lines: That's fantastic! As your biographer bot, I am excited to help you create a new memory"
