### ISSUE TITLE
Clarity on AI usage

### ISSUE THREAD

**Issue by Mookse** [MyLife-Services/mylife-maht#427]
There are no humans behind any of the chatting on the platform, everything is done through AI NL processing. We should endeavor to find implicit ways to identify that the agents you chat with are _not_ human - in general, LLMs by default present as AI; can override, we use in actor and character-bots

- [x] Visual elements indicating AI... ideas? They are already non-human thumbs
- [x] rollover icons -> purpose

@sheikita For the moment, there are now icons representing the intelligences; on rollover I show the text that meets these criteria. Obviously we can expand or improve this if valuable, let me know your thoughts if this is sufficient for demonstration MVP purposes.

**Comment by sheikita** [comment]
@Mookse The icons are great to help users visualize the different agents we have. Still, let's make sure we add during their introduction that they are "non-human" bot. 
On a side note, I asked the avatar and biographers agents if they were human and they replied not.  🥇
